let data=[],settings={},tab='downloading',speedHistory=Array(20).fill(0);const $=id=>document.getElementById(id);
async function api(u,o={}){const r=await fetch(u,o);let j={};try{j=await r.json()}catch{}if(!r.ok||j.error)throw Error(j.error||`HTTP ${r.status}`);return j}
function fmt(n){n=+n||0;if(n<1024)return `${Math.round(n)} B`;const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<3);return `${n.toFixed(i?1:0)} ${u[i]}`}
function eta(s){s=+s||0;if(!s)return '—';if(s<60)return `${s}s`;if(s<3600)return `${Math.floor(s/60)}m ${s%60}s`;return `${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`}
function esc(s){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function pct(d){return d.total_size?Math.min(100,d.downloaded_size/d.total_size*100):0}
function icon(n){const e=(n||'').split('.').pop().toLowerCase();return {iso:'◈',zip:'▣',rar:'▣','7z':'▣',mp4:'▶',mkv:'▶',webm:'▶',mp3:'♫',flac:'♫',pdf:'▤',doc:'▤',docx:'▤',apk:'▣',jpg:'▧',jpeg:'▧',png:'▧'}[e]||'↓'}
const CAT={video:['Video','▶'],audio:['Audio','♫'],document:['Document','▤'],archive:['Archive','▣'],image:['Image','▧'],app:['App / Game','▣'],other:['Other','↓']};
function categoryBadge(c){let x=CAT[c]||CAT.other;return `<span class="tag categoryTag">${x[1]} ${x[0]}</span>`}
function scheduleBadge(d){return d.scheduled_at?`<span class="tag scheduleTag">◷ Scheduled</span>`:''}
function tehranNowInput(addMin=0){const now=new Date(Date.now()+addMin*60000);const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const g=k=>f.find(x=>x.type===k)?.value||'';return `${g('year')}-${g('month')}-${g('day')}T${g('hour')}:${g('minute')}`}
function tehranDisplay(v){if(!v)return '';try{return new Intl.DateTimeFormat('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'}).format(new Date(v.replace(' ','T')+'+03:30'))}catch{return v}}
function scheduleField(){const n=tehranNowInput(),s=tehranNowInput(5),e=tehranNowInput(305);return `<div class="schedulePicker"><div class="scheduleHead"><div><b>Schedule download</b><small>Optional • Tehran time (Asia/Tehran)</small></div><label class="switch mini"><input id="scheduleOn" type="checkbox" onchange="toggleSchedulePicker()"><i></i></label></div><div id="schedulePickerBody" class="hidden"><div class="fieldRow"><label class="settingHint">Start time<input id="when" type="datetime-local" min="${n}" value="${s}"></label><label class="settingHint">End time<input id="scheduleEnd" type="datetime-local" min="${s}" value="${e}"></label></div><div class="tzHint">🕐 Timezone: <b>Asia/Tehran</b> • Download stops at End time and keeps partial data.</div></div></div>`}
function toggleSchedulePicker(){const on=$('scheduleOn')?.checked;$('schedulePickerBody')?.classList.toggle('hidden',!on);$('scheduleOn')?.parentElement?.classList.toggle('on',!!on)}

function card(d,done=false){const p=pct(d),live=d.status==='Downloading',scheduled=!!d.scheduled_at,canPause=live;return `<article class="card ${done?'completedCard':''} ${live?'activeDownloadCard':''}"><div class="cardTop"><div class="fileIcon">${icon(d.filename)}</div><div class="fileInfo"><div class="fileName" title="${esc(d.filename)}">${esc(d.filename)}</div><div class="fileSub"><i class="liveDot ${live?'on':''}"></i>${esc(d.status)} <span>•</span> ${esc(d.interface||'auto')} <span>•</span> ${d.threads} threads</div><div class="tagRow">${categoryBadge(d.category)}${scheduled?`<span class="tag scheduleTag">◷ Scheduled</span>`:''}</div></div><button class="moreBtn" onclick="showActions(${d.id})">⋮</button></div><div class="bar"><i style="width:${p}%"></i></div><div class="metricRow"><span>${fmt(d.downloaded_size)} / ${d.total_size?fmt(d.total_size):'?'}</span><b class="green">${fmt(d.speed)}/s</b><span>${eta(d.eta)}</span><b>${p.toFixed(0)}%</b></div>${scheduled?`<div class="scheduleInfo">◷ ${esc(tehranDisplay(d.scheduled_at))}${d.schedule_end_at?` → ${esc(tehranDisplay(d.schedule_end_at))}`:''}</div>`:''}${d.error?`<div class="error">${esc(d.error)}</div>`:''}<div class="cardActions"><button class="smallBtn primaryAction" onclick="act(${d.id},'${canPause?'pause':'resume'}')">${canPause?'Pause':'Resume'}</button>${!done?`<button class="smallBtn" onclick="showDetails(${d.id})">Details</button>`:''}<button class="smallBtn danger" onclick="removeItem(${d.id})">Delete</button></div></article>`}
function render(){const q=($('search')?.value||'').toLowerCase();let arr=data.filter(d=>!q||(d.filename+' '+d.url).toLowerCase().includes(q));const active=arr.filter(d=>d.status!=='Completed'&&d.status!=='Cancelled'),done=arr.filter(d=>d.status==='Completed');$('downCount').textContent=active.length;$('doneCount').textContent=done.length;$('tabDownloading').classList.toggle('active',tab==='downloading');$('tabDownloaded').classList.toggle('active',tab==='downloaded');let view=tab==='downloading'?active:done;$('list').innerHTML=view.length?view.map(d=>card(d,tab==='downloaded')).join(''):`<div class="empty">${tab==='downloading'?'No active downloads':'No completed downloads yet'}</div>`;const total=data.reduce((a,d)=>a+(+d.speed||0),0);$('total').textContent=fmt(total)+'/s';$('liveSpeed').textContent=fmt(total)+'/s';speedHistory.push(total);speedHistory=speedHistory.slice(-20);drawChart()}
function drawChart(){const max=Math.max(1024,...speedHistory),pts=speedHistory.map((v,i)=>`${i*(600/19)},${118-(v/max)*102}`).join(' ');$('sparkline').setAttribute('points',pts)}
function setTab(t){tab=t;render()}
async function refresh(){try{data=await api('/api/downloads');render()}catch(e){console.error(e)}}
async function act(i,a){try{await api(`/api/downloads/${i}/${a}`,{method:'POST'})}catch(e){alert(e.message)}await refresh()}
async function startAll(){return controlAll('start-all')}
async function stopAll(){return controlAll('pause-all')}
async function controlAll(a){const label=a==='start-all'?'Start all downloads?':'Stop all active downloads?';if(!confirm(label))return;try{await api(`/api/control/${a}`,{method:'POST'})}catch(e){alert(e.message)}await refresh()}
async function removeItem(i){if(confirm('Delete this download?')){try{await api(`/api/downloads/${i}`,{method:'DELETE'})}catch(e){alert(e.message)}await refresh()}}
function show(t,h,k='DOWNLOAD'){ $('title').textContent=t;$('modalKicker').textContent=k;$('form').innerHTML=h;$('modal').classList.remove('hidden') }
function closeModal(){$('modal').classList.add('hidden')}
function toggleSearch(){$('searchbar').classList.toggle('hidden');if(!$('searchbar').classList.contains('hidden'))$('search').focus()}
async function ifaceOpts(){const a=await api('/api/interfaces');return a.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${esc(x.ip)}</option>`).join('')}
async function browse(path=''){return api('/api/browse?path='+encodeURIComponent(path))}
function folderDialog(start,cb){openFolder(start,cb)}
async function openFolder(path,cb){try{const b=await browse(path);const rows=b.dirs.map(d=>`<button class="browseItem" onclick="openFolder(${JSON.stringify(d.path)},window.__folderCB)">📁 ${esc(d.name)}</button>`).join('')||'<div class="empty">No subfolders</div>';show('Choose download folder',`<div class="form"><div class="pathBox">${esc(b.path)}</div><div class="actionRow"><button class="secondary" ${b.parent?'':'disabled'} onclick="openFolder(${JSON.stringify(b.parent||b.path)},window.__folderCB)">↑ Parent</button><button class="primary" onclick="window.__folderCB(chosenPath.value);closeModal()">Use this folder</button></div><input id="chosenPath" value="${esc(b.path)}" aria-label="Path"><div class="browseList">${rows}</div></div>`,'LOCATION');window.__folderCB=cb}catch(e){alert(e.message)}}
function showActions(i){const d=data.find(x=>x.id===i);if(!d)return;show(esc(d.filename),`<div class="form"><div class="pill">${esc(d.status)}</div><div class="pathBox">${esc(d.filepath)}</div><div class="actionRow"><button class="secondary" onclick="act(${i},'resume');closeModal()">Resume</button><button class="secondary" onclick="act(${i},'pause');closeModal()">Pause</button></div><button class="secondary" onclick="removeItem(${i});closeModal()">Delete download</button></div>`,'DOWNLOAD')}

function showDetails(i){const d=data.find(x=>x.id===i);if(!d)return;show(esc(d.filename),`<div class="form"><div class="pill">${esc(d.status)}</div><label>URL<input value="${esc(d.url||'')}" readonly onclick="this.select()"></label><div class="pathBox">Size: ${d.total_size?fmt(d.total_size):'Unknown'}<br>Downloaded: ${fmt(d.downloaded_size)}<br>Path: ${esc(d.filepath||'')}</div><div class="pathBox">Interface: ${esc(d.interface||'auto')}<br>Threads: ${d.threads}<br>Category: ${esc(d.category||'other')}${d.scheduled_at?`<br>Start: ${esc(tehranDisplay(d.scheduled_at))}`:''}${d.schedule_end_at?`<br>End: ${esc(tehranDisplay(d.schedule_end_at))}`:''}</div></div>`,'FILE DETAILS')}
async function openAdd(){const opt=await ifaceOpts(),def=esc(settings.download_dir||'');show('Add download',`<div class="form"><div class="addMode"><button class="active">Single URL</button><button onclick="openBulk()">Multiple URLs</button></div><input id="u" placeholder="https://example.com/file.zip" autofocus><input id="fn" placeholder="File name (optional)"><div class="folderBox"><small>DOWNLOAD TO SERVER</small><strong id="folderText">${def}</strong><button onclick="folderDialog(folder.value,p=>{folder.value=p;folderText.textContent=p})">Choose folder</button><input id="folder" value="${def}" style="display:none"></div><div class="fieldRow"><label class="settingHint">Threads<select id="th">${[1,2,4,8,12,16].map(x=>`<option value="${x}" ${x==settings.default_threads?'selected':''}>${x}</option>`).join('')}</select></label><label class="settingHint">Interface<select id="nic">${opt}</select></label></div><div class="fieldRow"><label class="settingHint">File type<select id="cat"><option value="auto">Auto detect</option><option value="video">▶ Video</option><option value="audio">♫ Audio</option><option value="document">▤ Document</option><option value="archive">▣ Archive</option><option value="image">▧ Image</option><option value="app">▣ App / Game</option><option value="other">↓ Other</option></select></label></div>${scheduleField('Start at')}<button class="primary" onclick="addOne()">Add download</button></div>`,'ADD DOWNLOAD')}
async function addOne(){const u=$('u').value.trim();if(!u)return alert('Enter a URL.');try{await api('/api/downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u,filename:$('fn').value.trim(),folder:$('folder').value.trim(),threads:+$('th').value,interface:$('nic').value,scheduled_at:$('scheduleOn')?.checked?$('when').value:null,schedule_end_at:$('scheduleOn')?.checked?$('scheduleEnd').value:null,category:$('cat').value})});closeModal();tab='downloading';await refresh()}catch(e){alert(e.message)}}
async function openBulk(){const opt=await ifaceOpts(),def=esc(settings.download_dir||'');show('Add multiple downloads',`<div class="form"><div class="addMode"><button onclick="openAdd()">Single URL</button><button class="active">Multiple URLs</button></div><textarea id="urls" oninput="countUrls()" placeholder="Paste one URL per line…\n\nYou can paste 40, 100 or 500+ links."></textarea><div class="urlCount" id="urlCount">0 URLs</div><div class="folderBox"><small>DOWNLOAD TO SERVER</small><strong id="folderText">${def}</strong><button onclick="folderDialog(folder.value,p=>{folder.value=p;folderText.textContent=p})">Choose folder</button><input id="folder" value="${def}" style="display:none"></div><div class="fieldRow"><label class="settingHint">Threads<select id="th">${[1,2,4,8,12,16].map(x=>`<option value="${x}" ${x==settings.default_threads?'selected':''}>${x}</option>`).join('')}</select></label><label class="settingHint">Interface<select id="nic">${opt}</select></label></div><div class="fieldRow"><label class="settingHint">File type<select id="cat"><option value="auto">Auto detect per file</option><option value="video">▶ Video</option><option value="audio">♫ Audio</option><option value="document">▤ Document</option><option value="archive">▣ Archive</option><option value="image">▧ Image</option><option value="app">▣ App / Game</option><option value="other">↓ Other</option></select></label></div>${scheduleField('Start all at')}<button class="primary" onclick="bulk()">Add all to queue</button></div>`,'ADD DOWNLOADS')}
async function bulk(){const urls=$('urls').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!urls.length)return alert('Paste at least one URL.');try{const r=await api('/api/downloads/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({urls,folder:$('folder').value.trim(),threads:+$('th').value,interface:$('nic').value,scheduled_at:$('scheduleOn')?.checked?$('when').value:null,schedule_end_at:$('scheduleOn')?.checked?$('scheduleEnd').value:null,category:$('cat').value})});alert(`Added: ${r.added}\nDuplicates: ${r.duplicates}\nInvalid: ${r.invalid}`);closeModal();tab='downloading';await refresh()}catch(e){alert(e.message)}}
async function openDrawer(){try{const c=await api('/api/settings');settings=c;const scheduled=data.filter(d=>d.status==='Scheduled').length;$('drawerBody').innerHTML=`
<div class="settingBlock settingsHero"><div class="settingEyebrow">DOWNLOAD CONTROL</div><div class="settingsHeroTitle">Server downloads</div><div class="settingHint">Everything downloads directly to your Raspberry Pi.</div></div>
<div class="settingBlock"><div class="settingLabel">Folder for files</div><div class="settingValue" id="drawerFolder">${esc(c.download_dir)}</div><div class="settingHint">Current server destination</div><button class="settingButton" onclick="folderDialog(${JSON.stringify(c.download_dir)},p=>saveFolder(p))">Change download folder</button></div>
<div class="settingBlock rangeSetting"><div class="settingTop"><div><div class="settingLabel">Simultaneous downloads</div><div class="settingHint">How many files run at once</div></div><span class="rangeVal big" id="mcVal">${c.max_concurrent}</span></div><div class="rangeLine"><span class="rangeIcon">⇄</span><input id="mc" type="range" min="1" max="8" value="${c.max_concurrent}" oninput="mcVal.textContent=this.value" onchange="saveQuickSettings()"><span class="rangeEnd">8</span></div></div>
<div class="settingBlock rangeSetting"><div class="settingTop"><div><div class="settingLabel">Threads per download</div><div class="settingHint">Parallel connections for each file</div></div><span class="rangeVal big" id="thVal">${c.default_threads}</span></div><div class="rangeLine"><span class="rangeIcon">↯</span><input id="thd" type="range" min="1" max="16" value="${c.default_threads}" oninput="thVal.textContent=this.value" onchange="saveQuickSettings()"><span class="rangeEnd">16</span></div></div>
<div class="settingBlock rangeSetting"><div class="settingTop"><div><div class="settingLabel">Download speed</div><div class="settingHint">Global bandwidth limit</div></div><span class="rangeVal big" id="speedVal">${c.global_speed_limit?fmt(c.global_speed_limit)+'/s':'MAX'}</span></div><div class="rangeLine"><span class="rangeIcon">⇩</span><input id="speed" type="range" min="0" max="50" value="${c.global_speed_limit?Math.min(50,Math.round(c.global_speed_limit/1024/1024)):0}" oninput="speedVal.textContent=this.value==0?'MAX':this.value+' MB/s'" onchange="saveQuickSettings()"><span class="rangeEnd">50M</span></div></div>
<div class="settingBlock toggleSetting"><div><div class="settingLabel">Smart download</div><div class="settingHint">Automatic queue management</div></div><button class="switch on"><i></i></button></div>
<div class="settingBlock toggleSetting"><div><div class="settingLabel">Auto-resume</div><div class="settingHint">Resume after server restart</div></div><button class="switch ${c.auto_resume?'on':''}" onclick="toggleResume(this)"><i></i></button></div>
<div class="settingBlock scheduleCard"><div class="settingIcon">◷</div><div class="scheduleText"><div class="settingLabel">Scheduled downloads</div><div class="settingHint">${scheduled} waiting in the schedule</div></div><button class="settingButton compact" onclick="openAdd();closeDrawer()">＋ Schedule download</button></div>
<div class="settingBlock quickActions"><button class="drawerAction accentAction" onclick="startAll();closeDrawer()">▶ Start all</button><button class="drawerAction stopAction" onclick="stopAll();closeDrawer()">Ⅱ Stop all</button><button class="drawerAction" onclick="openBulk();closeDrawer()">＋ Add multiple URLs</button><button class="drawerAction" onclick="openAdd();closeDrawer()">＋ Add single URL</button><button class="drawerAction" onclick="openSettings();closeDrawer()">⚙ Advanced settings</button></div>`;$('drawer').classList.remove('hidden')}catch(e){alert(e.message)}}
function closeDrawer(){$('drawer').classList.add('hidden')}
async function saveFolder(p){try{const r=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({download_dir:p,download_roots:[p,'/mnt/hdd2','/home/games']})});settings=r;closeModal();openDrawer()}catch(e){alert(e.message)}}
async function saveQuickSettings(){try{const speed=+$('speed').value||0;const r=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({max_concurrent:+$('mc').value,default_threads:+$('thd').value,global_speed_limit:speed*1024*1024})});settings=r}catch(e){console.error(e)}}
async function toggleResume(el){el.classList.toggle('on');try{await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({auto_resume:el.classList.contains('on')})})}catch(e){alert(e.message)}}
async function openSettings(){const c=await api('/api/settings');settings=c;show('Advanced settings',`<div class="form"><label>Default download folder<input id="root" value="${esc(c.download_dir)}"></label><label>Allowed server roots<input id="roots" value="${esc((c.download_roots||[]).join(', '))}"></label><label>Max simultaneous downloads<input id="mc2" type="number" min="1" max="8" value="${c.max_concurrent}"></label><label>Default threads<input id="dt" type="number" min="1" max="16" value="${c.default_threads}"></label><label>Retry count<input id="rc" type="number" min="0" max="20" value="${c.retry_count}"></label><button class="primary" onclick="saveSettings()">Save settings</button></div>`,'SETTINGS')}
async function saveSettings(){try{const roots=$('roots').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({download_dir:$('root').value.trim(),download_roots:roots,max_concurrent:+$('mc2').value,default_threads:+$('dt').value,retry_count:+$('rc').value})});settings=r;closeModal();await refresh()}catch(e){alert(e.message)}}
$('search').oninput=render;new EventSource('/api/events').onmessage=e=>{try{data=JSON.parse(e.data);render()}catch{}};refresh();api('/api/settings').then(x=>settings=x);
